### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by wivern-co-uk** [g105b/markdown-to-html#2]
Hi @g105b, thanks for such a tiny script.

I would like to use markdown-to-html for a commercial website, would you mind to add a license file to clarify possible usages. Thanks in advance!

https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by g105b** [comment]
Sure, no problem. Happy to licence this as MIT.

If you make loads of money using this, please consider buying me a coffee :) http://paypal.me/g105b

**Comment by g105b** [comment]
Also, as this library is very very old, it might be a good idea for me to take a look at updating it, adding tests, etc. Would happily accept PRs for this, but I'll try and find the time to improve it knowing that someone is using it in the wild.

Have fun!
